# Capítulo 5 - Ejercicios

## Nombre:

### Escoger dos problemas a resolver. 

### Ejercicio 1

Basado en el programa `primos.py` y la función `enc_primos.py`, escriba un programa que genere una matriz en la cual se organicen los números primos. Pero en este caso, organícelos en forma de hélice, es decir
```
2x2 matrix
[[ 2.  3.]
 [ 7.  5.]]
3x3 matrix
[[ 17.  19.  23.]
 [ 13.   2.   3.]
 [ 11.   7.   5.]]
4x4 matrix
[[ 17.  19.  23.  29.]
 [ 13.   2.   3.  31.]
 [ 11.   7.   5.  37.]
 [ 53.  47.  43.  41.]]
```
Permita que se pueda crear la matriz de diferentes tamaños (`5x5`, `6x6`, ...).

In [1]:
#Función que encuentra la cantidad de primos presentes desde el número dos
#hasta "maxx", hace totalmente lo mismo que la hecha en clase 
#por parte del profesor Germán. Al final de la celda se pone a prueba esta 
#función con maxx = 100. Nota: esta función también se encuentra en el módulo
#ubicado en el DDS del computador

def primos(maxx):
    
    #Función que devuelve una matriz y la cantidad de datos en esta matriz
    #los cuales son los primos presentes desde 2 hasta el número máximo "maxx"
    #input:
    #   maxx: número hasta el cual se quiere buscar los números primos
    #output:
    #   cont: número de primos encontrado
    #   prim: matriz que contiene los primos encontrados
    
    #Se importan los módulos necesarios.
    
    import numpy as np
    
    #Se crea la matriz de 0's de los cuales, dependiendo del índice,
    #se van a reemplazar por 1 si no son primos, teniendo 0's en lugares
    #cuyo índice corresponda a un primo. Además se crea la variable "cont" 
    
    a = np.zeros(maxx)
    cont = 0
    
    #Se evalúa i, que va a ser el índice de la matriz inicial a, mediante
    #un for loop
    
    for i in range(1,maxx):
        if a[i] == 0:
            
            #Se eliminan los múltiplos los números primos
            
            for c in range(i+2,maxx+1):
                if c%(i+1) == 0:
                    a[c-1] = 1
            
            #Se aumenta de a 1 cada vez que se encuentra un número primo
            
            cont += 1
    
    #Al finalizar de poner los 1 en la matriz inicial a
    #se procede a crear una matriz de 0's, con el número de datos
    #igual a los primos encontrados
    
    prim = np.zeros(cont)    
    n1 = -1 
    
    #Se va llenando la matriz descrita anteriormente con los primos encontrados
    
    for i1 in range(1,maxx):
        if a[i1] == 0:
            n1 += 1
            prim[n1] = i1 + 1
    
    #Finalmente se devuelven las valriables cont y prim
    
    return cont, prim

    #Prueba de la función con maxx = 100

a,b = primos(100)
print('La cantidad de números primos de 0 a 100 son',a,', y estos son:',b)

La cantidad de números primos de 0 a 100 son 25 , y estos son: [ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29. 31. 37. 41. 43. 47. 53. 59. 61.
 67. 71. 73. 79. 83. 89. 97.]


In [2]:
#Se crea el programa para preguntarle repetidamente al usuario el tamaño 
#de la matriz hélice que desee

a = 1
while a > 0:
    a = int(input('introduzca el número de filas (o columnas) que desea para su\
 matriz hélice de números primos, 0 o negativo para terminar el      programa: '))
    
    if a <= 0:
        print('Muchas gracias por usar el programa, hasta luego ')
        break
    
    else:

        #Se importan los módulos necesarios
        
        import numpy as np

        #Se hace el vector del cual se procede a hacer la matriz hélice a
        #partir de la variable 'a', que es el numero de filas o de columnas
        #de la matriz cuadrada. Al no conocerse cual es número primo más
        #grande presente en esta matriz, se hace lo siguiente:

        #A partir de la función 'primos' descrita en la celda anterior se obtienen
        #dos variables, la primera es la cantidad de datos que contiene, y la 
        #segunda son los primos en cuestión, como la función 'primos' busca 
        #los números primos hasta un numero máximo, en caso de que la cantidad 
        #de datos no sea suficientemente grande para llenar la matriz hélice, 
        #se establece que este número máximo sea cada vez mayor hasta encontrar la cantidad
        #de primos necesaria para crear la matriz. el valor (a**2)*11 se cree
        #suficientemente grande como para actuar de número máximo

        cont,prim = primos((a**2)*11)

        #'numM' es el lado que va a poseer la matriz hélice 

        numM = a 
        while cont < a**2:                                          
            a += 1
            cont,prim = primos(((a)**2)*11)

        #se crea la matriz inicial "m", que es el primer dato del vector 
        #'prim'

        if numM > 0:
            m = np.array([prim[0]],dtype=int)
            cm = 1

        #Se crea el for loop que va a crear consecutivamente las matrices 2x2, después
        #3x3, y así consecutivamente hasta numM x numM, la matriz 1 x 1 no se tiene
        #en cuenta 

        for cm in range(2,numM+1):

            #Se crea la matriz cuadrada donde todos los datos son 0's del tal manera

            m0 = np.zeros([cm,cm],dtype=int)

            #Al crearse la nueva matriz  'm0' donde se va a pegar la anteior matriz 'm',
            #pueden darse dos casos, al ser el número de filas o columnas de 'm0' par,
            #la última fila y la última columna serán las llenadas, mientras que si 'm0'
            #es impar, serán llenadas la primera fila, y la primera columna. Debido a esto
            #los condicionales descritos a continuación.

            #Caso donde el número de filas de 'm0' sea impar:

            if cm%2 != 0:

                #Al ser impar 'm0' la anterior matriz 'm' se tendrá que ubicar en la fila 1
                #y columna 1

                m0[1:,1:] = m

                #Se establece la nueva matriz'm' a partir de la matriz 'm0' mediante el
                #comando np.copy()

                m = np.copy(m0)

                #Se establece el lugar f1 para la fila, y c1 para la columna, para
                #posteriormente llenar la matriz 'm'. La razón de esto se detalla
                #más adelante

                f1 = cm-1
                c1 = 1

                #Se crea el for loop para ir extrayendo mediante el índice 'i' los datos
                #del vector 'prim' en orden, acá es importante recalcar que los índices
                #necesarios de por ejemplo una matriz de 3x3 son solo los de la fila 
                #y columan faltantes, por lo tanto no serán necesarios los índices de
                #la matríz 2x2, lo que se traduce en que i se encuentra desde
                #el número de filas de la anterior matriz elevado al cuadrado,
                #ya que ya introdujimos todos esos datos de aquellos índices,
                #hasta el número de filas de la matriz presente elevado al cuadrado,
                #ya que hasta estos índices se van a encontrar los datos que van a
                #llenar la presente matriz

                for i in range((cm-1)**2,cm**2):

                        #Al ser impar la matriz 'm' se van a llenar primero la
                        #primera columna, desde la última fila (f1), hasta la 
                        #primera fila(m[0,0]), para evitar que el programa
                        #intente introducir datos en lugares no correspondientes,
                        #por ejemplo m[-1,0] se establece la condición de que 
                        #m[0,0]tiene que estar vacío.

                        if m[0,0] == 0:
                            m[f1,0] = prim[i]
                            f1 -= 1

                        #En este caso parecido al anterior se llena la primera fila
                        #comenzando con la primera columna hasta llegar a la última,
                        #como en el if anterior, es necesaria una condición, en este 
                        #caso m[0,última columna] == 0

                        elif m[0,cm-1] == 0:
                            m[0,c1] = prim[i]
                            c1 += 1

            #Caso donde la matriz 'm0' tenga numero de filas par, se obvian algunas
            #explicaciones del código debido a que algunas filas de este son las
            #mismas explicadas anteriormente

            elif cm%2 == 0:  

                #En caso de que 'm0' tenga un tamaño de 2x2(o lo que es lo mismo
                #el tamaño de 'm' sea de 1, se debe introducir 'm' a 'm0' como sigue.
                #Si no es así, la siguiente parte del programa nos va a botar error,
                #ya que el tamaño de una matriz 1x1 ocuparía el espacio m0[0,0], no el 
                #esapcio m0[0:1,0:1].

                if len(m) == 1:
                    m0[0,0] = m

                #En caso de que la matriz 'm0' no sea de 2x2 se introduce la matriz 'm'
                #a 'm0' como sigue, teniendo en cuenta que 'm' va a ocupar desde la fila
                #y columna 1 (m0[0,0]) hasta la fila y columna del tamaño de la matriz
                #'m' m[cm-1,cm-1].

                else:
                    m0[0:cm-1,0:cm-1] = m
                m = np.copy(m0)
                f1 = 0
                c1 = cm-2
                for i in range((cm-1)**2,cm**2):

                        #En este caso se llena la última columna comenzando desde la 
                        #primera fila hasta la primera fila, en este caso se utiliza
                        #el condicional m[ultima fila,ultima columna]=0

                        if m[cm-1,cm-1] == 0:
                            m[f1,cm-1] = prim[i]
                            f1 += 1

                        #Al terminar de llenarse la última columna, se comienza a llenar
                        #la última fila, comenzando desde la última columna hasta llegar 
                        #la primera, en este caso el condicional es m[última fila,primera
                        #columna]=0

                        elif m[cm-1,0] == 0:
                            m[cm-1,c1] = prim[i]
                            c1 -= 1

            #Finalmente es necesario que se impriman las diferentes matrices hélice creadas,
            #y un titulito que nos diga su tamaño

        print('Matriz hélice',cm,'x',cm,':')
        print(m)
    

introduzca el número de filas (o columnas) que desea para su matriz hélice de números primos, 0 o negativo para terminar el      programa: 1
Matriz hélice 1 x 1 :
[2]
introduzca el número de filas (o columnas) que desea para su matriz hélice de números primos, 0 o negativo para terminar el      programa: 3
Matriz hélice 3 x 3 :
[[17 19 23]
 [13  2  3]
 [11  7  5]]
introduzca el número de filas (o columnas) que desea para su matriz hélice de números primos, 0 o negativo para terminar el      programa: 4
Matriz hélice 4 x 4 :
[[17 19 23 29]
 [13  2  3 31]
 [11  7  5 37]
 [53 47 43 41]]
introduzca el número de filas (o columnas) que desea para su matriz hélice de números primos, 0 o negativo para terminar el      programa: 10
Matriz hélice 10 x 10 :
[[367 373 379 383 389 397 401 409 419 421]
 [359 191 193 197 199 211 223 227 229 431]
 [353 181  73  79  83  89  97 101 233 433]
 [349 179  71  17  19  23  29 103 239 439]
 [347 173  67  13   2   3  31 107 241 443]
 [337 167  61  11   7   5  3

### Ejercicio 2

Un análisis simple de una serie de datos incluye el cálculo del promedio (mean) y la desviación estandard (std). Sin embargo, algunos datos tienen distribuciones estadísticas que no son normales (gaussiana), y una mejor descripción del valor medio de los datos se obtiene con la mediana (median). Para calcular la mediana, se requiere organizar los datos de manera ascendente y así determinar la mediana. Una función que permite reorganizar un arreglo de números utiliza el método de `quicksort`, adjunto en el módulo `quicksort.py`.

Cree dos arreglos de 50 y 51 números aleatorios con `numpy` y con funciones propias determine el promedio, desviación estándar y la mediana del arreglo. No utilice funciones pre-existentes de Python para el cálculo, pero compare sus resultados con las funciones `np.mean` y `np.median`. 

Puede usar
```
C = np.random.normal(0,1,51)
```
para crear su arreglo. 

Desplegar los resultados y discutir, si hay alguna diferencia, la razón. 


In [3]:
#En esta celda se procede a hacer las diferentes funciones que se van a 
#utilizar para el programa. Debido a que no es posible utilizar 
#funciones ya existentes en python, se crean las funcoines
#tamvec() y sumvec(), utilizadas para encontrar el tamaño del vector
#y la suma de sus datos respectivamente.

def tamvec(c):
    
    #Función que nos indica el tamaño de un vector.
    #   Input:
    #     c : vector al cual se le calcula el tamaño
    #   Output
    #     tam : tamaño del vector 
    
    #Se crea la variable tam:
    
    tam = 0
    
    #Mediante un for loop se establece que para cada 'i', que es un dato
    #contenido en la matriz 'c', se le sume 1 a tam, siendo tam inicialmente
    #0
    
    for i in c:
        tam += 1
    
    #Finalmente se devuelve el tamaño de la matriz: 'tam'
    
    return tam

def sumvec(c):
    
    #Función que nos indica cual es la suma de todos los datos contenidos en un
    #vector.
    #   Input:
    #     c : matriz al cual se le va a calcular 'sum'
    #   Output:
    #     sumi : suma de todos los datos contenidos en 'c'
    
    #Se crea la variable 'sumi' con un valor inicial de 0
    
    sumi = 0
    
    #Mediante un for loop se va sumando 'i', que son los valores encontrados 
    #en el vector 'c', a 'sumi'.
    
    for i in c:
        sumi += i
    
    #Finalmente se devuelve la sumatoria de todos los valores encontrados en 
    #'c': 'sumi'
    
    return sumi
    
#Ya que se crearon las funcionoes necesarias para las definiciones que nos pide
#el punto del taller, se procede a crear estas definiciones:
    
def promvec(c):
    
    #Promve() nos indica el promedio de los datos enccontrados en un vector.
    #   Input:
    #     c : Matriz a la cual calcularle el promedio
    #   Output:
    #     prom : Promedio de los datos de la matriz 'c'
    
    #El promedio es simplemente la suma de los datos (sumvec()) sobre 
    #el número de datos (tamvec()) del vector 'c'
    
    prom = sumvec(c)/tamvec(c)
    
    #Se devuelve el valor 'prom'
    
    return prom 

def dees(c):
    
    #Esta función calcula la desviación estándar de los datos encontrados
    #en un vector.
    #   Input:
    #     c: Matriz a la cual se le va a calcular la desviación estándar
    #   Output:
    #     DeEs
    
    #Se crea la variable 'sUm', con un valor inicial a 0. Ésta variable 
    #va a ser posteriormente la suma de cada valor encontrado en el vector
    #'c' menos el promedio, y elevado al cuadrado.
    
    sUm = 0
    
    #Mediante la función promvec() se define el promedio de los datos 
    #dentro del vector 'c'
    
    p = promvec(c)
    
    #Mediante un for loop se le va sumando repetidamente el resultado
    #de cada dato del vector menos el promedio elevado al cuadrado mediante
    #indexando con c[i]
    
    for i in range(tamvec(c)):
        
        #La operación como tal de cada cálculo da como resultado 'enpa', que 
        #se va sumando a 'sUm' en cada iteración del for loop
        
        enpa = (c[i]-p)**2
        sUm += enpa
    
    #Por definición la desviación estándar ('DeEs') es la raíz cuadrada de la
    #varianza (Vari), que a su vez es la sumatoria de todos los datos menos el promedio
    #elevados al cuadrado ('sUm') sobre el número de datos (tamvec(c)), de calcula por lo 
    #tanto
    
    Vari = sUm/tamvec(c)
    DeEs = Vari**(1/2)
    
    #Finalmente se devuelve la desviación estándar 'DeEs'
    
    return DeEs

def mediana(c):
    #Función que calcula la mediana a los datos encontrados en un vector.
    #   Input:
    #     c: Matriz a la cualse le va a calcular la mediana 
    #   Output:
    #     mena: Mediana de los datos del vector 'c'
    
    #Se importa el módulo facilitado por el profesor para organizar los datos del 
    #vector 'c', de manera ascendente, y se reorganiza 'c'
    
    import quicksort as qs
    c = qs.quicksort(c)
    
    #La mediana va a depender si la cantidad de datos a los cuales se le va a calcular
    #es par o impar, en caso de que sea impar la mediana será el dato intermedio, y 
    #en caso de que sea par, será el promedio de los dos datos intermedios, por lo tanto
    #se incorporan dos condicionales que nos digan si el número de datos es par o impar
    
    if tamvec(c)%2 != 0:
        
        #Si el tamaño del vector es impar entonces dividir el tamaño en dos dará un número
        #con cifra decimal .5, si por ejemplo el vector tiene 3 datos, el de en medio será
        #el 2 dato, sin embargo debido a que python comienza indexando en 0, el dato deseado
        #será vector[1], además si dividimos 3 en 2 dará 1.5, por tanto se le resta 0.5 a 1.5
        #para obtener 1, esta es la misma lógica para todos los vectores cuyos números de datos
        #sean impares.
        
        i = int((tamvec(c)/2)-0.5)
        mena = c[i]

    if tamvec(c)%2 == 0:
        
        #En caso de el tamaño del vector sea par, se va a buscar el promedio del os dos datos
        #encontrados justo en el medio de este vector, ajustando esto y la indexación
        #de python que comienza en 0 se obtiene como resultado 
        
        i = int(tamvec(c)/2)
        mena = (c[i]+c[i-1])/2   
    
    #Finalmente se devuelve la mediana: 'mena'
    
    return mena  

In [4]:
#Ya que se tienen las funciones necesarias para calcular los datos pedidos
#por el profesor se procede a esto con dos matrices diferentes, y además
#comparando el resultado de las funciones propias con las funciones 
#dentro del módulo numpy 

#Creación de las dos matrices

m1 = np.random.normal(0,1,51)
m2 = np.random.normal(0,1,50)

#Se crean dos vectores con los resultados mediante funciones propias (vector llamado 'p') y 
#funciones de numpy (vector llamado 'n') para cada una de las dos matrices

p1 = np.array([promvec(m1),dees(m1),mediana(m1)])
n1 = np.array([np.mean(m1),np.std(m1),np.median(m1)])
p2 = np.array([promvec(m2),dees(m2),mediana(m2)])
n2 = np.array([np.mean(m2),np.std(m2),np.median(m2)])

#Se procede a imprimir los datos para mayor facilidad de análisis, comenzando
#con la primera matriz

t = np.array(['promedio','desviación estándar','mediana'])
print('Para la primera matriz')
print('             Cálculo|       Funciones propias|      Funciones de numpy|')
for i in range(tamvec(p1)):
    print('%20s|'%(t[i]),'%23.20f|'%(p1[i]),'%23.20f|'%(n1[i]))

#Y siguiendo con la segunda matriz    
    
print('\nPara la segunda matriz')
print('             Cálculo|       Funciones propias|      Funciones de numpy|')
for i in range(tamvec(p2)):
    
    print('%20s|'%(t[i]),'%23.20f|'%(p2[i]),'%23.20f|'%(n2[i]))

#Se imprimen las conclusiones
    
print('\n\nSe observa que las funciones propias dan un resultado muy parecido al de las funciones de numpy en el caso del \
cálculo del     promedio y desviación estándar, con una diferencia de aproximadamente 1e-16, en el caso de la mediana los \
resultados son       siempre iguales. La pequeña diferencia en el promedio y la desviación estándar puede deberse a la presición \
del computador')


Para la primera matriz
             Cálculo|       Funciones propias|      Funciones de numpy|
            promedio|  0.09232054521242276379|  0.09232054521242273604|
 desviación estándar|  1.14520870626154613880|  1.14520870626154613880|
             mediana| -0.04106912255584604932| -0.04106912255584604932|

Para la segunda matriz
             Cálculo|       Funciones propias|      Funciones de numpy|
            promedio| -0.21662019632661061452| -0.21662019632661067003|
 desviación estándar|  0.87025313999539954946|  0.87025313999539943843|
             mediana| -0.18157283100368951101| -0.18157283100368951101|


Se observa que las funciones propias dan un resultado muy parecido al de las funciones de numpy en el caso del cálculo del     promedio y desviación estándar, con una diferencia de aproximadamente 1e-16, en el caso de la mediana los resultados son       siempre iguales. La pequeña diferencia en el promedio y la desviación estándar puede deberse a la presición del computado

### Ejercicio 3

En Geología estructural, tectónica o sismología muchas veces se estudia los esfuerzos y se describen con el tensor de esfuerzos. Suponga que tenemos un tensor de esfuerzos horizontales (solo 2 dimensiones)
$$
\tau = 
\begin{bmatrix}
\tau_{xx} & \tau_{xy}\\
\tau_{yx} & \tau_{yy}\\
\end{bmatrix}
$$

Para un tensor de esfuerzos, siempre es posible encontrar una dirección de tal forma que no haya esfuerzos de cizalla ($\tau_{xy}=\tau_{yx}=0$). Cuando esto se obtiene, se dice que se encontró los ejes principales de esfuerzo. 
$$
\tau^R = 
\begin{bmatrix}
\tau_{1} & 0\\
0 & \tau_{2}\\
\end{bmatrix}
$$

Por convención, los ejes principales están organizados de tal forma que $|\tau_1|>|\tau_2|$.

Escriba un programa que determine que ángulo debe rotar la matriz $\mathbf{\tau}$ 
$$
\tau = \begin{bmatrix}
-27.0 & -7.1\\
-7.1 & -13.0\\
\end{bmatrix} = 
\begin{bmatrix}
\tau_{xx} & \tau_{xy}\\
\tau_{yx} & \tau_{yy}\\
\end{bmatrix}
$$

para obtener (lo más cercano posible) un tensor de esfuerzos con sus ejes principales. Para rotar el tensor un ángulo $\alpha$ debe realizar la operación matricial:
$$
\tau^R = R\tau R^T
$$
donde 
$$
R = 
\begin{bmatrix}
\cos(\alpha) & -\sin(\alpha)\\
\sin(\alpha) & \cos(\alpha)\\
\end{bmatrix}
$$

**Ayuda** Recuerde que debe cambiar el ángulo a radianes para calcular el coseno. Permita que el programa haga la búsqueda del ángulo por Ud., por ejemplo con un `for` loop.

**Nota**: El mismo (y mejor) resultado se puede obtener utilizando algoritmos de algebra lineal, por ejemplo utilizando los *eigenvalues* y *eigenvectors* de la matriz. Pero esto es para más adelante (no usar en esta tarea). 


In [5]:
import numpy as np

#Se introduce el vector de Tau dado en el enunciado

Tau = np.array([[-27.,-7.1],[-7.1,-13]])

#Se establece un valor mínimo del cual se compara TauR para ir seleccionando 
#cada vez números menores en los índices TauR[0,1]

utili = np.array([[0,0.3],[0.3,0]])

#Se establece un for loop para ir buscando en cada ángulo, la presición deter-
#mina la velocidad del programa.

for i in range(360000):
    
    #Se obtiene el ángulo con la presición deseada y se pasa a radianes
    
    ang = i*0.001
    ra = np.radians(ang)
    
    #Se crea la matriz R a partir del ángulo anterior y la transpuesta de esta
    #mediante np.transpose
    
    R = np.array([[np.cos(ra),-np.sin(ra)],[np.sin(ra),np.cos(ra)]])
    RT = np.transpose(R)
    
    #Se crea TauR utilizando la función np.matmul
    
    TauR = np.matmul(np.matmul(R,Tau),RT)
    
    #Mediante un comando if se selecciona la matriz donde Tau[0,1] sea cada vez
    #más cercano a 0, y además, donde |t1| sea mayor que |t2|, también se guarda
    #el respectivo ángulo
    
    if abs(TauR[0,1]) <abs(utili[0,1]) and abs(TauR[0,0]) > abs(TauR[1,1]):
        utili = TauR
        angr = ang

#Se imprimen los resultados del programa
        
print('Se observa que es necesario rotar la matriz un ángulo',angr,'° para obtener un tensor de esfuerzos con sus\
ejes principales:\n',utili)

Se observa que es necesario rotar la matriz un ángulo 157.297 ° para obtener un tensor de esfuerzos con susejes principales:
 [[-2.99704564e+01 -6.02505826e-05]
 [-6.02505826e-05 -1.00295436e+01]]


In [2]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
Numero_mínimo = 1
for i in np.array([1,3,5,1,0.2]):
    if i < Numero_mínimo:
        Numero_mínimo = i

In [4]:
3//2

1

In [5]:
4//2


2

In [6]:
4.32//2

2.0